app_platform:
    resource: "@AppPlatformBundle/Resources/config/routing.yml"
    prefix:   /

app_admin:
    resource: "@AppAdminBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
