<?php

namespace App\PlatformBundle\Repository;

/**
 * detail_produitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class detail_produitRepository extends \Doctrine\ORM\EntityRepository
{
}
