app_admin_gestionproduit:
    path:     /gestion_produit
    defaults: { _controller: AppAdminBundle:Gestion:produit }

app_admin_gestionpromo:
    path:     /gestion_promo
    defaults: { _controller: AppAdminBundle:Gestion:promo }

app_admin_menu:
    path:     /menu
    defaults: { _controller: AppAdminBundle:Gestion:menu }

app_admin_homepage:
    path:     /
    defaults: { _controller: AppAdminBundle:Default:index }